---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/dynamic-translation-json-files"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@progress/kendo-angular-*"
